<?php
/**
 * OrganisationDailyTrafficObject
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/CodericEcosystem/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/CodericEcosystem/emnify-php-sdk
 * Do not edit the class manually.
 */

namespace Emnify\EmnifySdk\Model;

use \ArrayAccess;
use \Emnify\EmnifySdk\ObjectSerializer;

/**
 * OrganisationDailyTrafficObject Class Doc Comment
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */
class OrganisationDailyTrafficObject implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Organisation daily traffic object';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'cost' => 'string',
        'currency_id' => 'string',
        'currency' => '\Emnify\EmnifySdk\Model\Currency',
        'traffic_type_id' => 'string',
        'traffic_type' => '\Emnify\EmnifySdk\Model\OrganisationDailyTrafficObjectTrafficType',
        'volume' => 'string',
        'volume_rx' => 'string',
        'volume_tx' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'cost' => null,
        'currency_id' => null,
        'currency' => null,
        'traffic_type_id' => null,
        'traffic_type' => null,
        'volume' => null,
        'volume_rx' => null,
        'volume_tx' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cost' => 'cost',
        'currency_id' => 'currency_id',
        'currency' => 'currency',
        'traffic_type_id' => 'traffic_type_id',
        'traffic_type' => 'traffic_type',
        'volume' => 'volume',
        'volume_rx' => 'volume_rx',
        'volume_tx' => 'volume_tx'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cost' => 'setCost',
        'currency_id' => 'setCurrencyId',
        'currency' => 'setCurrency',
        'traffic_type_id' => 'setTrafficTypeId',
        'traffic_type' => 'setTrafficType',
        'volume' => 'setVolume',
        'volume_rx' => 'setVolumeRx',
        'volume_tx' => 'setVolumeTx'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cost' => 'getCost',
        'currency_id' => 'getCurrencyId',
        'currency' => 'getCurrency',
        'traffic_type_id' => 'getTrafficTypeId',
        'traffic_type' => 'getTrafficType',
        'volume' => 'getVolume',
        'volume_rx' => 'getVolumeRx',
        'volume_tx' => 'getVolumeTx'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cost'] = isset($data['cost']) ? $data['cost'] : null;
        $this->container['currency_id'] = isset($data['currency_id']) ? $data['currency_id'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['traffic_type_id'] = isset($data['traffic_type_id']) ? $data['traffic_type_id'] : null;
        $this->container['traffic_type'] = isset($data['traffic_type']) ? $data['traffic_type'] : null;
        $this->container['volume'] = isset($data['volume']) ? $data['volume'] : null;
        $this->container['volume_rx'] = isset($data['volume_rx']) ? $data['volume_rx'] : null;
        $this->container['volume_tx'] = isset($data['volume_tx']) ? $data['volume_tx'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cost
     *
     * @return string
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param string $cost Total cost
     *
     * @return $this
     */
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets currency_id
     *
     * @return string
     */
    public function getCurrencyId()
    {
        return $this->container['currency_id'];
    }

    /**
     * Sets currency_id
     *
     * @param string $currency_id currency_id
     *
     * @return $this
     */
    public function setCurrencyId($currency_id)
    {
        $this->container['currency_id'] = $currency_id;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \Emnify\EmnifySdk\Model\Currency
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \Emnify\EmnifySdk\Model\Currency $currency currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets traffic_type_id
     *
     * @return string
     */
    public function getTrafficTypeId()
    {
        return $this->container['traffic_type_id'];
    }

    /**
     * Sets traffic_type_id
     *
     * @param string $traffic_type_id traffic_type_id
     *
     * @return $this
     */
    public function setTrafficTypeId($traffic_type_id)
    {
        $this->container['traffic_type_id'] = $traffic_type_id;

        return $this;
    }

    /**
     * Gets traffic_type
     *
     * @return \Emnify\EmnifySdk\Model\OrganisationDailyTrafficObjectTrafficType
     */
    public function getTrafficType()
    {
        return $this->container['traffic_type'];
    }

    /**
     * Sets traffic_type
     *
     * @param \Emnify\EmnifySdk\Model\OrganisationDailyTrafficObjectTrafficType $traffic_type traffic_type
     *
     * @return $this
     */
    public function setTrafficType($traffic_type)
    {
        $this->container['traffic_type'] = $traffic_type;

        return $this;
    }

    /**
     * Gets volume
     *
     * @return string
     */
    public function getVolume()
    {
        return $this->container['volume'];
    }

    /**
     * Sets volume
     *
     * @param string $volume Total consumption (`volume_rx` + `volume_tx`)
     *
     * @return $this
     */
    public function setVolume($volume)
    {
        $this->container['volume'] = $volume;

        return $this;
    }

    /**
     * Gets volume_rx
     *
     * @return string
     */
    public function getVolumeRx()
    {
        return $this->container['volume_rx'];
    }

    /**
     * Sets volume_rx
     *
     * @param string $volume_rx * For traffic type `5` (`Data`): Downloaded data * For traffic type `6` (`SMS`): SMS MT
     *
     * @return $this
     */
    public function setVolumeRx($volume_rx)
    {
        $this->container['volume_rx'] = $volume_rx;

        return $this;
    }

    /**
     * Gets volume_tx
     *
     * @return string
     */
    public function getVolumeTx()
    {
        return $this->container['volume_tx'];
    }

    /**
     * Sets volume_tx
     *
     * @param string $volume_tx * For traffic type `5` (`Data`): Uploaded data * For traffic type `6` (`SMS`): SMS MO
     *
     * @return $this
     */
    public function setVolumeTx($volume_tx)
    {
        $this->container['volume_tx'] = $volume_tx;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
