<?php
/**
 * Apiv1tariffProfileTariffTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace Emnify\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * Apiv1tariffProfileTariffTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv1tariffProfileTariff
 * @package     Emnify\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/Emnify/emnify-php-sdk
 */
class Apiv1tariffProfileTariffTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Apiv1tariffProfileTariff"
     */
    public function testApiv1tariffProfileTariff()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "organisation_id"
     */
    public function testPropertyOrganisationId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "tariff_status_id"
     */
    public function testPropertyTariffStatusId()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "default_sms_mt_rate"
     */
    public function testPropertyDefaultSmsMtRate()
    {
    }

    /**
     * Test attribute "default_sms_mo_rate"
     */
    public function testPropertyDefaultSmsMoRate()
    {
    }

    /**
     * Test attribute "sim_issued_rate"
     */
    public function testPropertySimIssuedRate()
    {
    }

    /**
     * Test attribute "sim_activated_rate"
     */
    public function testPropertySimActivatedRate()
    {
    }

    /**
     * Test attribute "sim_suspended_rate"
     */
    public function testPropertySimSuspendedRate()
    {
    }

    /**
     * Test attribute "sim_activation_rate"
     */
    public function testPropertySimActivationRate()
    {
    }

    /**
     * Test attribute "sim_reactivation_rate"
     */
    public function testPropertySimReactivationRate()
    {
    }

    /**
     * Test attribute "sim_suspension_rate"
     */
    public function testPropertySimSuspensionRate()
    {
    }

    /**
     * Test attribute "sim_termination_rate"
     */
    public function testPropertySimTerminationRate()
    {
    }

    /**
     * Test attribute "data_throttle_id"
     */
    public function testPropertyDataThrottleId()
    {
    }

    /**
     * Test attribute "data_blocksize_id"
     */
    public function testPropertyDataBlocksizeId()
    {
    }

    /**
     * Test attribute "public"
     */
    public function testPropertyPublic()
    {
    }

    /**
     * Test attribute "tariff_category_id"
     */
    public function testPropertyTariffCategoryId()
    {
    }

    /**
     * Test attribute "visibility_id"
     */
    public function testPropertyVisibilityId()
    {
    }

    /**
     * Test attribute "tariff_currency_category_id"
     */
    public function testPropertyTariffCurrencyCategoryId()
    {
    }

    /**
     * Test attribute "used_count"
     */
    public function testPropertyUsedCount()
    {
    }

    /**
     * Test attribute "assigned_count"
     */
    public function testPropertyAssignedCount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }
}
