<?php
/**
 * Apiv2dataStreamDestinationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/CodericEcosystem/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/CodericEcosystem/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * Apiv2dataStreamDestinationTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv2dataStreamDestination
 * @package     CodericEcosystem\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/CodericEcosystem/emnify-php-sdk
 */
class Apiv2dataStreamDestinationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Apiv2dataStreamDestination"
     */
    public function testApiv2dataStreamDestination()
    {
    }

    /**
     * Test attribute "connection_type"
     */
    public function testPropertyConnectionType()
    {
    }

    /**
     * Test attribute "format"
     */
    public function testPropertyFormat()
    {
    }

    /**
     * Test attribute "credentials"
     */
    public function testPropertyCredentials()
    {
    }
}
