<?php
/**
 * Apiv1organisationorgIdtariffPlanTariffPlanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/CodericEcosystem/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/CodericEcosystem/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * Apiv1organisationorgIdtariffPlanTariffPlanTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv1organisationorgIdtariffPlanTariffPlan
 * @package     CodericEcosystem\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/CodericEcosystem/emnify-php-sdk
 */
class Apiv1organisationorgIdtariffPlanTariffPlanTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Apiv1organisationorgIdtariffPlanTariffPlan"
     */
    public function testApiv1organisationorgIdtariffPlanTariffPlan()
    {
    }

    /**
     * Test attribute "organisation_id"
     */
    public function testPropertyOrganisationId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "tariff_plan_type_id"
     */
    public function testPropertyTariffPlanTypeId()
    {
    }

    /**
     * Test attribute "min_tariff_plan_runtime_id"
     */
    public function testPropertyMinTariffPlanRuntimeId()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "tariff_plan_runtime_id"
     */
    public function testPropertyTariffPlanRuntimeId()
    {
    }

    /**
     * Test attribute "owner_organisation_id"
     */
    public function testPropertyOwnerOrganisationId()
    {
    }

    /**
     * Test attribute "public_for_child_organisations"
     */
    public function testPropertyPublicForChildOrganisations()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "activation_date"
     */
    public function testPropertyActivationDate()
    {
    }

    /**
     * Test attribute "deprecation_date"
     */
    public function testPropertyDeprecationDate()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "yearly_rate"
     */
    public function testPropertyYearlyRate()
    {
    }

    /**
     * Test attribute "sim_activation_fee"
     */
    public function testPropertySimActivationFee()
    {
    }

    /**
     * Test attribute "max_active_sims"
     */
    public function testPropertyMaxActiveSims()
    {
    }

    /**
     * Test attribute "add_active_sims_rate"
     */
    public function testPropertyAddActiveSimsRate()
    {
    }

    /**
     * Test attribute "add_active_sim_batch"
     */
    public function testPropertyAddActiveSimBatch()
    {
    }

    /**
     * Test attribute "max_service_profiles"
     */
    public function testPropertyMaxServiceProfiles()
    {
    }

    /**
     * Test attribute "max_tariff_profiles"
     */
    public function testPropertyMaxTariffProfiles()
    {
    }

    /**
     * Test attribute "max_users"
     */
    public function testPropertyMaxUsers()
    {
    }

    /**
     * Test attribute "minimum_runtime"
     */
    public function testPropertyMinimumRuntime()
    {
    }

    /**
     * Test attribute "api_access_allowed"
     */
    public function testPropertyApiAccessAllowed()
    {
    }

    /**
     * Test attribute "vpn_access"
     */
    public function testPropertyVpnAccess()
    {
    }

    /**
     * Test attribute "private"
     */
    public function testPropertyPrivate()
    {
    }

    /**
     * Test attribute "dtype"
     */
    public function testPropertyDtype()
    {
    }

    /**
     * Test attribute "evaluation"
     */
    public function testPropertyEvaluation()
    {
    }

    /**
     * Test attribute "expiry_time"
     */
    public function testPropertyExpiryTime()
    {
    }

    /**
     * Test attribute "billing_disabled"
     */
    public function testPropertyBillingDisabled()
    {
    }

    /**
     * Test attribute "used_count"
     */
    public function testPropertyUsedCount()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "service_level"
     */
    public function testPropertyServiceLevel()
    {
    }

    /**
     * Test attribute "federation_allowed"
     */
    public function testPropertyFederationAllowed()
    {
    }

    /**
     * Test attribute "factory_test_mode_allowed"
     */
    public function testPropertyFactoryTestModeAllowed()
    {
    }
}
