<?php
/**
 * CreateCloudConnectVPNRequest1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/CodericEcosystem/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/CodericEcosystem/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * CreateCloudConnectVPNRequest1Test Class Doc Comment
 *
 * @category    Class
 * @description CreateCloudConnectVPNRequest1
 * @package     CodericEcosystem\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/CodericEcosystem/emnify-php-sdk
 */
class CreateCloudConnectVPNRequest1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateCloudConnectVPNRequest1"
     */
    public function testCreateCloudConnectVPNRequest1()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "public_ip"
     */
    public function testPropertyPublicIp()
    {
    }

    /**
     * Test attribute "psk"
     */
    public function testPropertyPsk()
    {
    }

    /**
     * Test attribute "asn"
     */
    public function testPropertyAsn()
    {
    }

    /**
     * Test attribute "premise_cidr"
     */
    public function testPropertyPremiseCidr()
    {
    }

    /**
     * Test attribute "inside_cidr"
     */
    public function testPropertyInsideCidr()
    {
    }
}
