<?php
/**
 * EndpointRuntimeDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * EndpointRuntimeDataTest Class Doc Comment
 *
 * @category    Class
 * @description EndpointRuntimeData
 * @package     CodericEcosystem\EmnifySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EndpointRuntimeDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EndpointRuntimeData"
     */
    public function testEndpointRuntimeData()
    {
    }

    /**
     * Test attribute "msc"
     */
    public function testPropertyMsc()
    {
    }

    /**
     * Test attribute "sgsn"
     */
    public function testPropertySgsn()
    {
    }

    /**
     * Test attribute "sgsn_ip_address"
     */
    public function testPropertySgsnIpAddress()
    {
    }
}
