<?php
/**
 * GetMonthlyOrganisationStatsResponseSimTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetMonthlyOrganisationStatsResponseSimTest Class Doc Comment
 *
 * @category    Class
 * @description Amount of SIMs per SIM status where the selected organisation is either the customer organisation or the issuer organisation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetMonthlyOrganisationStatsResponseSimTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetMonthlyOrganisationStatsResponseSim"
     */
    public function testGetMonthlyOrganisationStatsResponseSim()
    {
    }

    /**
     * Test attribute "issued"
     */
    public function testPropertyIssued()
    {
    }

    /**
     * Test attribute "factory_mode"
     */
    public function testPropertyFactoryMode()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "suspended"
     */
    public function testPropertySuspended()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }
}
