<?php
/**
 * GetMonthlyOrganisationStatsResponseInclusiveVolumeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetMonthlyOrganisationStatsResponseInclusiveVolumeTest Class Doc Comment
 *
 * @category    Class
 * @description GetMonthlyOrganisationStatsResponseInclusiveVolume
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetMonthlyOrganisationStatsResponseInclusiveVolumeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetMonthlyOrganisationStatsResponseInclusiveVolume"
     */
    public function testGetMonthlyOrganisationStatsResponseInclusiveVolume()
    {
    }

    /**
     * Test attribute "unpooled"
     */
    public function testPropertyUnpooled()
    {
    }

    /**
     * Test attribute "pooled"
     */
    public function testPropertyPooled()
    {
    }
}
