<?php
/**
 * GetOrganisationActiveTariffPlanResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/CodericEcosystem/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/CodericEcosystem/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * GetOrganisationActiveTariffPlanResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetOrganisationActiveTariffPlanResponse
 * @package     CodericEcosystem\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/CodericEcosystem/emnify-php-sdk
 */
class GetOrganisationActiveTariffPlanResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetOrganisationActiveTariffPlanResponse"
     */
    public function testGetOrganisationActiveTariffPlanResponse()
    {
    }

    /**
     * Test attribute "organisation_id"
     */
    public function testPropertyOrganisationId()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "sim_activated_rate"
     */
    public function testPropertySimActivatedRate()
    {
    }

    /**
     * Test attribute "sim_activated_idle_rate"
     */
    public function testPropertySimActivatedIdleRate()
    {
    }

    /**
     * Test attribute "sim_suspended_rate"
     */
    public function testPropertySimSuspendedRate()
    {
    }

    /**
     * Test attribute "sim_suspended_active_rate"
     */
    public function testPropertySimSuspendedActiveRate()
    {
    }

    /**
     * Test attribute "sim_activated_amount"
     */
    public function testPropertySimActivatedAmount()
    {
    }

    /**
     * Test attribute "applied_price"
     */
    public function testPropertyAppliedPrice()
    {
    }

    /**
     * Test attribute "tariff_plan"
     */
    public function testPropertyTariffPlan()
    {
    }

    /**
     * Test attribute "tariff_plan_runtime"
     */
    public function testPropertyTariffPlanRuntime()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "applied_rate"
     */
    public function testPropertyAppliedRate()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "service_level"
     */
    public function testPropertyServiceLevel()
    {
    }
}
