<?php
/**
 * GetOrganisationActiveTariffPlanResponseTariffPlanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * GetOrganisationActiveTariffPlanResponseTariffPlanTest Class Doc Comment
 *
 * @category    Class
 * @description GetOrganisationActiveTariffPlanResponseTariffPlan
 * @package     CodericEcosystem\EmnifySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetOrganisationActiveTariffPlanResponseTariffPlanTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetOrganisationActiveTariffPlanResponseTariffPlan"
     */
    public function testGetOrganisationActiveTariffPlanResponseTariffPlan()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "activation_date"
     */
    public function testPropertyActivationDate()
    {
    }

    /**
     * Test attribute "deprecation_date"
     */
    public function testPropertyDeprecationDate()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "yearly_rate"
     */
    public function testPropertyYearlyRate()
    {
    }

    /**
     * Test attribute "sim_activation_fee"
     */
    public function testPropertySimActivationFee()
    {
    }

    /**
     * Test attribute "max_active_sims"
     */
    public function testPropertyMaxActiveSims()
    {
    }

    /**
     * Test attribute "add_active_sims_rate"
     */
    public function testPropertyAddActiveSimsRate()
    {
    }

    /**
     * Test attribute "add_active_sim_batch"
     */
    public function testPropertyAddActiveSimBatch()
    {
    }

    /**
     * Test attribute "max_service_profiles"
     */
    public function testPropertyMaxServiceProfiles()
    {
    }

    /**
     * Test attribute "max_tariff_profiles"
     */
    public function testPropertyMaxTariffProfiles()
    {
    }

    /**
     * Test attribute "max_users"
     */
    public function testPropertyMaxUsers()
    {
    }

    /**
     * Test attribute "minimum_runtime"
     */
    public function testPropertyMinimumRuntime()
    {
    }

    /**
     * Test attribute "api_access_allowed"
     */
    public function testPropertyApiAccessAllowed()
    {
    }

    /**
     * Test attribute "vpn_access"
     */
    public function testPropertyVpnAccess()
    {
    }

    /**
     * Test attribute "evaluation"
     */
    public function testPropertyEvaluation()
    {
    }

    /**
     * Test attribute "expiry_time"
     */
    public function testPropertyExpiryTime()
    {
    }

    /**
     * Test attribute "used_count"
     */
    public function testPropertyUsedCount()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }
}
