<?php
/**
 * InlineResponse20012Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace Emnify\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse20012Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20012
 * @package     Emnify\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/Emnify/emnify-php-sdk
 */
class InlineResponse20012Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse20012"
     */
    public function testInlineResponse20012()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "organisation_id"
     */
    public function testPropertyOrganisationId()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "sim_activated_rate"
     */
    public function testPropertySimActivatedRate()
    {
    }

    /**
     * Test attribute "sim_activated_idle_rate"
     */
    public function testPropertySimActivatedIdleRate()
    {
    }

    /**
     * Test attribute "sim_suspended_rate"
     */
    public function testPropertySimSuspendedRate()
    {
    }

    /**
     * Test attribute "sim_suspended_active_rate"
     */
    public function testPropertySimSuspendedActiveRate()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "federation_allowed"
     */
    public function testPropertyFederationAllowed()
    {
    }

    /**
     * Test attribute "factory_test_mode_allowed"
     */
    public function testPropertyFactoryTestModeAllowed()
    {
    }

    /**
     * Test attribute "service_level"
     */
    public function testPropertyServiceLevel()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "applied_rate"
     */
    public function testPropertyAppliedRate()
    {
    }

    /**
     * Test attribute "price_model"
     */
    public function testPropertyPriceModel()
    {
    }

    /**
     * Test attribute "tariff_plan"
     */
    public function testPropertyTariffPlan()
    {
    }
}
