<?php
/**
 * InlineResponse20010Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace Emnify\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse20010Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20010
 * @package     Emnify\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/Emnify/emnify-php-sdk
 */
class InlineResponse20010Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse20010"
     */
    public function testInlineResponse20010()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "accept_attachment_expiry_date"
     */
    public function testPropertyAcceptAttachmentExpiryDate()
    {
    }

    /**
     * Test attribute "termination_date"
     */
    public function testPropertyTerminationDate()
    {
    }

    /**
     * Test attribute "aws_transit_gateway_attachment_id"
     */
    public function testPropertyAwsTransitGatewayAttachmentId()
    {
    }

    /**
     * Test attribute "aws_vpn_connection_id"
     */
    public function testPropertyAwsVpnConnectionId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }
}
