<?php
/**
 * InlineResponse2006Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace Emnify\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2006Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2006
 * @package     Emnify\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/Emnify/emnify-php-sdk
 */
class InlineResponse2006Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2006"
     */
    public function testInlineResponse2006()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
    }

    /**
     * Test attribute "data_stream_type"
     */
    public function testPropertyDataStreamType()
    {
    }

    /**
     * Test attribute "relation_resolution"
     */
    public function testPropertyRelationResolution()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
