<?php
/**
 * RetrieveaSingleServiceProfileresponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * RetrieveaSingleServiceProfileresponseTest Class Doc Comment
 *
 * @category    Class
 * @description RetrieveaSingleServiceProfileresponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RetrieveaSingleServiceProfileresponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RetrieveaSingleServiceProfileresponse"
     */
    public function testRetrieveaSingleServiceProfileresponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "allowed_3g"
     */
    public function testPropertyAllowed3g()
    {
    }

    /**
     * Test attribute "allowed_4g"
     */
    public function testPropertyAllowed4g()
    {
    }

    /**
     * Test attribute "allowed_nb_iot"
     */
    public function testPropertyAllowedNbIot()
    {
    }

    /**
     * Test attribute "apply_sms_quota"
     */
    public function testPropertyApplySmsQuota()
    {
    }

    /**
     * Test attribute "apply_data_quota"
     */
    public function testPropertyApplyDataQuota()
    {
    }

    /**
     * Test attribute "retail"
     */
    public function testPropertyRetail()
    {
    }

    /**
     * Test attribute "sms_p2p_int"
     */
    public function testPropertySmsP2pInt()
    {
    }

    /**
     * Test attribute "sms_p2p_ext"
     */
    public function testPropertySmsP2pExt()
    {
    }

    /**
     * Test attribute "prepaid"
     */
    public function testPropertyPrepaid()
    {
    }

    /**
     * Test attribute "nipdp"
     */
    public function testPropertyNipdp()
    {
    }

    /**
     * Test attribute "used_count"
     */
    public function testPropertyUsedCount()
    {
    }

    /**
     * Test attribute "api_callback"
     */
    public function testPropertyApiCallback()
    {
    }

    /**
     * Test attribute "api_secret"
     */
    public function testPropertyApiSecret()
    {
    }

    /**
     * Test attribute "moc_callback"
     */
    public function testPropertyMocCallback()
    {
    }

    /**
     * Test attribute "esme_interface_type"
     */
    public function testPropertyEsmeInterfaceType()
    {
    }

    /**
     * Test attribute "breakout_region"
     */
    public function testPropertyBreakoutRegion()
    {
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
    }
}
