<?php
/**
 * RetrieveEndpointStatisticsresponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the model.
 */

namespace Emnify\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * RetrieveEndpointStatisticsresponseTest Class Doc Comment
 *
 * @category    Class
 * @description RetrieveEndpointStatisticsresponse
 * @package     Emnify\EmnifySdk
 * @author      Coderic Development Team
 * @link        https://github.com/Emnify/emnify-php-sdk
 */
class RetrieveEndpointStatisticsresponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RetrieveEndpointStatisticsresponse"
     */
    public function testRetrieveEndpointStatisticsresponse()
    {
    }

    /**
     * Test attribute "last_month"
     */
    public function testPropertyLastMonth()
    {
    }

    /**
     * Test attribute "current_month"
     */
    public function testPropertyCurrentMonth()
    {
    }

    /**
     * Test attribute "last_hour"
     */
    public function testPropertyLastHour()
    {
    }
}
