<?php
/**
 * SimEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * SimEntryTest Class Doc Comment
 *
 * @category    Class
 * @description SimEntry
 * @package     CodericEcosystem\EmnifySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SimEntryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SimEntry"
     */
    public function testSimEntry()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "iccid"
     */
    public function testPropertyIccid()
    {
    }

    /**
     * Test attribute "eid"
     */
    public function testPropertyEid()
    {
    }

    /**
     * Test attribute "production_date"
     */
    public function testPropertyProductionDate()
    {
    }

    /**
     * Test attribute "activation_date"
     */
    public function testPropertyActivationDate()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "customer_org"
     */
    public function testPropertyCustomerOrg()
    {
    }

    /**
     * Test attribute "issuer_org"
     */
    public function testPropertyIssuerOrg()
    {
    }

    /**
     * Test attribute "reseller_org"
     */
    public function testPropertyResellerOrg()
    {
    }

    /**
     * Test attribute "endpoint"
     */
    public function testPropertyEndpoint()
    {
    }

    /**
     * Test attribute "imsi"
     */
    public function testPropertyImsi()
    {
    }

    /**
     * Test attribute "msisdn"
     */
    public function testPropertyMsisdn()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }
}
