<?php
/**
 * SMSQuotaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CodericEcosystem\EmnifySdk;

use PHPUnit\Framework\TestCase;

/**
 * SMSQuotaTest Class Doc Comment
 *
 * @category    Class
 * @description SMSQuota
 * @package     CodericEcosystem\EmnifySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SMSQuotaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SMSQuota"
     */
    public function testSMSQuota()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "last_volume_added"
     */
    public function testPropertyLastVolumeAdded()
    {
    }

    /**
     * Test attribute "last_status_change_date"
     */
    public function testPropertyLastStatusChangeDate()
    {
    }

    /**
     * Test attribute "auto_refill"
     */
    public function testPropertyAutoRefill()
    {
    }

    /**
     * Test attribute "threshold_percentage"
     */
    public function testPropertyThresholdPercentage()
    {
    }

    /**
     * Test attribute "threshold_volume"
     */
    public function testPropertyThresholdVolume()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "action_on_exhaustion"
     */
    public function testPropertyActionOnExhaustion()
    {
    }
}
