<?php
/**
 * AuthenticationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the endpoint.
 */

namespace Emnify\EmnifySdk;

use Emnify\EmnifySdk\Configuration;
use Emnify\EmnifySdk\ApiException;
use Emnify\EmnifySdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AuthenticationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */
class AuthenticationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for authenticate
     *
     * Retrieve Authentication Token.
     *
     */
    public function testAuthenticate()
    {
    }

    /**
     * Test case for postMfa
     *
     * Create an MFA key.
     *
     */
    public function testPostMfa()
    {
    }

    /**
     * Test case for userMfaByIdPatch
     *
     * Activate MFA key.
     *
     */
    public function testUserMfaByIdPatch()
    {
    }

    /**
     * Test case for userMfaByUserIdAndKeyIdDelete
     *
     * Delete an MFA key.
     *
     */
    public function testUserMfaByUserIdAndKeyIdDelete()
    {
    }

    /**
     * Test case for userMfaStatusGet
     *
     * List MFA key Statuses.
     *
     */
    public function testUserMfaStatusGet()
    {
    }

    /**
     * Test case for userMfaTrustedDeviceByUserIdAndDeviceIdDelete
     *
     * Delete a Trusted Device.
     *
     */
    public function testUserMfaTrustedDeviceByUserIdAndDeviceIdDelete()
    {
    }

    /**
     * Test case for userMfaTrustedDeviceByUserIdGet
     *
     * List Trusted Devices.
     *
     */
    public function testUserMfaTrustedDeviceByUserIdGet()
    {
    }

    /**
     * Test case for userMfaTypeGet
     *
     * List MFA key types.
     *
     */
    public function testUserMfaTypeGet()
    {
    }
}
