<?php
/**
 * IPAddressSpacesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CodericEcosystem\EmnifySdk;

use CodericEcosystem\EmnifySdk\Configuration;
use CodericEcosystem\EmnifySdk\ApiException;
use CodericEcosystem\EmnifySdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IPAddressSpacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IPAddressSpacesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for ipAddressSpaceAvailableByIpAddressVersionGet
     *
     * Get Random Address Spaces.
     *
     */
    public function testIpAddressSpaceAvailableByIpAddressVersionGet()
    {
    }

    /**
     * Test case for ipAddressSpaceByIdDelete
     *
     * Release an IP Address Space from an Organisation.
     *
     */
    public function testIpAddressSpaceByIdDelete()
    {
    }

    /**
     * Test case for ipAddressSpaceByIdPut
     *
     * Assign an IP Address Space to an Organisation.
     *
     */
    public function testIpAddressSpaceByIdPut()
    {
    }

    /**
     * Test case for ipAddressSpaceGet
     *
     * List IP Address Spaces.
     *
     */
    public function testIpAddressSpaceGet()
    {
    }
}
