<?php
/**
 * ServiceProfilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the endpoint.
 */

namespace Emnify\EmnifySdk;

use Emnify\EmnifySdk\Configuration;
use Emnify\EmnifySdk\ApiException;
use Emnify\EmnifySdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServiceProfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */
class ServiceProfilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addTrafficLimit
     *
     * Add Traffic Limit to Service Profile.
     *
     */
    public function testAddTrafficLimit()
    {
    }

    /**
     * Test case for deleteQuotaByServiceProfileId
     *
     * Remove all quotas of assigned endpoints.
     *
     */
    public function testDeleteQuotaByServiceProfileId()
    {
    }

    /**
     * Test case for removeTrafficLimit
     *
     * Remove Traffic Limit from a Service Profile.
     *
     */
    public function testRemoveTrafficLimit()
    {
    }

    /**
     * Test case for serviceProfileByProfileIdDelete
     *
     * Delete a Service Profile.
     *
     */
    public function testServiceProfileByProfileIdDelete()
    {
    }

    /**
     * Test case for serviceProfileByProfileIdGet
     *
     * Retrieve a Service Profile.
     *
     */
    public function testServiceProfileByProfileIdGet()
    {
    }

    /**
     * Test case for serviceProfileByProfileIdPatch
     *
     * Update Service Profile.
     *
     */
    public function testServiceProfileByProfileIdPatch()
    {
    }

    /**
     * Test case for serviceProfileGet
     *
     * List Service Profiles.
     *
     */
    public function testServiceProfileGet()
    {
    }

    /**
     * Test case for serviceProfilePost
     *
     * Create Service Profile.
     *
     */
    public function testServiceProfilePost()
    {
    }

    /**
     * Test case for serviceProfileServiceByProfileAndServiceDelete
     *
     * Remove a Service from a Service Profile.
     *
     */
    public function testServiceProfileServiceByProfileAndServiceDelete()
    {
    }

    /**
     * Test case for serviceProfileServiceByProfileAndServicePut
     *
     * Add a Service to a Service Profile.
     *
     */
    public function testServiceProfileServiceByProfileAndServicePut()
    {
    }
}
