<?php
/**
 * ServiceLookupsAndConfigurationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/Emnify/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/Emnify/emnify-php-sdk
 * Please update the test case below to test the endpoint.
 */

namespace Emnify\EmnifySdk;

use Emnify\EmnifySdk\Configuration;
use Emnify\EmnifySdk\ApiException;
use Emnify\EmnifySdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServiceLookupsAndConfigurationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Emnify\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/Emnify/emnify-php-sdk
 */
class ServiceLookupsAndConfigurationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for dnsByIdDelete
     *
     * Delete DNS config.
     *
     */
    public function testDnsByIdDelete()
    {
    }

    /**
     * Test case for dnsGet
     *
     * List DNS Configs.
     *
     */
    public function testDnsGet()
    {
    }

    /**
     * Test case for dnsPost
     *
     * Create DNS config.
     *
     */
    public function testDnsPost()
    {
    }

    /**
     * Test case for serviceGet
     *
     * List Services.
     *
     */
    public function testServiceGet()
    {
    }

    /**
     * Test case for serviceTrafficLimitByIdGet
     *
     * Get Service Traffic Limit.
     *
     */
    public function testServiceTrafficLimitByIdGet()
    {
    }

    /**
     * Test case for trafficLimitGet
     *
     * List Traffic Limits.
     *
     */
    public function testTrafficLimitGet()
    {
    }
}
