<?php
/**
 * TariffProfilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */

/**
 * emnify Rest API
 *
 * Rest API resources of the emnify System.
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/CodericEcosystem/emnify-php-sdk.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/CodericEcosystem/emnify-php-sdk
 * Please update the test case below to test the endpoint.
 */

namespace CodericEcosystem\EmnifySdk;

use CodericEcosystem\EmnifySdk\Configuration;
use CodericEcosystem\EmnifySdk\ApiException;
use CodericEcosystem\EmnifySdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TariffProfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  CodericEcosystem\EmnifySdk
 * @author   Coderic Development Team
 * @link     https://github.com/CodericEcosystem/emnify-php-sdk
 */
class TariffProfilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for tariffProfileByIdDelete
     *
     * Delete Tariff Profile.
     *
     */
    public function testTariffProfileByIdDelete()
    {
    }

    /**
     * Test case for tariffProfileByIdGet
     *
     * Tariff Profile Details.
     *
     */
    public function testTariffProfileByIdGet()
    {
    }

    /**
     * Test case for tariffProfileByIdPatch
     *
     * Update Tariff Profile.
     *
     */
    public function testTariffProfileByIdPatch()
    {
    }

    /**
     * Test case for tariffProfileCoverageByTpIdGet
     *
     * List Tariff Profile Coverage.
     *
     */
    public function testTariffProfileCoverageByTpIdGet()
    {
    }

    /**
     * Test case for tariffProfileGet
     *
     * List Tariff Profiles.
     *
     */
    public function testTariffProfileGet()
    {
    }

    /**
     * Test case for tariffProfileInclusiveVolumeAssignment
     *
     * Assign Inclusive Volume to Tarriff Profile.
     *
     */
    public function testTariffProfileInclusiveVolumeAssignment()
    {
    }

    /**
     * Test case for tariffProfileInclusiveVolumeRemoveAssignment
     *
     * Unassign Inclusive Volume from Tariff Profile.
     *
     */
    public function testTariffProfileInclusiveVolumeRemoveAssignment()
    {
    }

    /**
     * Test case for tariffProfilePost
     *
     * Create Tariff Profile.
     *
     */
    public function testTariffProfilePost()
    {
    }

    /**
     * Test case for tariffProfileRatezoneSelectionByTpIdAndRzIdDelete
     *
     * Delete Ratezone from Tariff Profile.
     *
     */
    public function testTariffProfileRatezoneSelectionByTpIdAndRzIdDelete()
    {
    }

    /**
     * Test case for tariffProfileRatezoneSelectionByTpIdAndRzIdPut
     *
     * Assign Ratezone to Tarriff Profile.
     *
     */
    public function testTariffProfileRatezoneSelectionByTpIdAndRzIdPut()
    {
    }
}
